using System;
using System.Collections.Generic;

namespace Redskull.Class
{
    internal static class UILocalization
    {
        private static readonly Dictionary<string, string> ExactTranslations = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Aim Assist"] = "ช่วยเล็ง",
            ["Aim Config"] = "ตั้งค่าการเล็ง",
            ["Predictions"] = "คาดการณ์เป้า",
            ["Auto Trigger"] = "ยิงอัตโนมัติ",
            ["FOV Config"] = "ตั้งค่า FOV",
            ["ESP Config"] = "ตั้งค่า ESP",
            ["Model Settings"] = "ตั้งค่าโมเดล",
            ["Settings Menu"] = "ตั้งค่าทั่วไป",
            ["Theme Settings"] = "ตั้งค่าธีม",
            ["Screen Settings"] = "ตั้งค่าหน้าจอ",
            ["Theme Color"] = "สีธีม",
            ["Current Theme Color"] = "สีธีมปัจจุบัน",
            ["Focus Display"] = "หน้าจอที่ใช้งาน",
            ["Primary Display Selected"] = "เลือกหน้าจอหลักแล้ว",
            ["No displays detected"] = "ไม่พบหน้าจอ",
            ["Primary"] = "หลัก",

            ["Constant AI Tracking"] = "ติดตามเป้าตลอดเวลา",
            ["Sticky Aim"] = "ล็อกเป้า",
            ["Sticky Aim Threshold"] = "ระยะคงล็อกเป้า",
            ["Aim Keybind"] = "ปุ่มช่วยเล็ง",
            ["Second Aim Keybind"] = "ปุ่มช่วยเล็งสำรอง",
            ["Mouse Movement Method"] = "วิธีส่งคำสั่งเมาส์",
            ["Movement Path"] = "รูปแบบการเคลื่อนเมาส์",
            ["Detection Area Type"] = "วิธีเลือกเป้าหมาย",
            ["Aiming Boundaries Alignment"] = "ตำแหน่งเล็งในกรอบเป้า",
            ["Mouse Sensitivity (+/-)"] = "ความไวเมาส์ (+/-)",
            ["Mouse Jitter"] = "การสั่นเมาส์เล็กน้อย",
            ["Y Axis Percentage Adjustment"] = "ปรับแกน Y แบบเปอร์เซ็นต์",
            ["X Axis Percentage Adjustment"] = "ปรับแกน X แบบเปอร์เซ็นต์",
            ["Y Offset (Up/Down)"] = "ชดเชยแกน Y (ขึ้น/ลง)",
            ["Y Offset (%)"] = "ชดเชยแกน Y (%)",
            ["X Offset (Left/Right)"] = "ชดเชยแกน X (ซ้าย/ขวา)",
            ["X Offset (%)"] = "ชดเชยแกน X (%)",
            ["Prediction Method"] = "วิธีคาดการณ์",
            ["Kalman Lead Time"] = "เวลานำเป้า Kalman",
            ["WiseTheFox Lead Time"] = "เวลานำเป้า WiseTheFox",
            ["Shalloe Lead Multiplier"] = "ตัวคูณนำเป้า Shalloe",
            ["EMA Smoothening"] = "ทำให้การเล็งนุ่มขึ้น",
            ["Cursor Check"] = "ตรวจตำแหน่งเคอร์เซอร์",
            ["Spray Mode"] = "โหมดยิงต่อเนื่อง",
            ["Auto Trigger Delay"] = "หน่วงเวลาก่อนยิงอัตโนมัติ",
            ["FOV"] = "แสดงวง FOV",
            ["Dynamic FOV"] = "FOV แบบปรับได้",
            ["Third Person Support"] = "รองรับมุมมองบุคคลที่สาม",
            ["Dynamic FOV Keybind"] = "ปุ่ม FOV แบบปรับได้",
            ["FOV Style"] = "รูปแบบ FOV",
            ["Circle"] = "วงกลม",
            ["Rectangle"] = "สี่เหลี่ยม",
            ["FOV Color"] = "สี FOV",
            ["FOV Size"] = "ขนาด FOV",
            ["Dynamic FOV Size"] = "ขนาด FOV แบบปรับได้",
            ["Show Detected Player"] = "แสดงกรอบเป้าหมาย",
            ["Show AI Confidence"] = "แสดงความมั่นใจ AI",
            ["Show Tracers"] = "แสดงเส้นชี้เป้า",
            ["Tracer Position"] = "ตำแหน่งเริ่มเส้นชี้เป้า",
            ["Top"] = "บน",
            ["Middle"] = "กลาง",
            ["Bottom"] = "ล่าง",
            ["Detected Player Color"] = "สีกรอบเป้าหมาย",
            ["AI Confidence Font Size"] = "ขนาดข้อความความมั่นใจ AI",
            ["Corner Radius"] = "ความโค้งมุม",
            ["Border Thickness"] = "ความหนาขอบ",
            ["Opacity"] = "ความโปร่งใส",
            ["Image Size"] = "ขนาดภาพ",
            ["Target Class"] = "ประเภทเป้าหมาย",
            ["Best Confidence"] = "มั่นใจสูงสุด",
            ["AI Minimum Confidence"] = "ค่าความมั่นใจขั้นต่ำของ AI",
            ["Enable Model Switch Keybind"] = "เปิดใช้ปุ่มสลับโมเดล",
            ["Model Switch Keybind"] = "ปุ่มสลับโมเดล",
            ["Emergency Stop Keybind"] = "ปุ่มหยุดฉุกเฉิน",
            ["Collect Data While Playing"] = "เก็บข้อมูลระหว่างเล่น",
            ["Auto Label Data"] = "ติดป้ายข้อมูลอัตโนมัติ",
            ["Mouse Background Effect"] = "เอฟเฟกต์พื้นหลังตามเมาส์",
            ["UI TopMost"] = "แสดงหน้าต่างทับทุกโปรแกรม",
            ["Debug Mode"] = "โหมดดีบัก",
            ["Save Config"] = "บันทึกคอนฟิก",
            ["Screen Capture Method"] = "วิธีจับภาพหน้าจอ",
            ["StreamGuard"] = "โหมดซ่อนบนสตรีม",
            ["Refresh Displays"] = "รีเฟรชหน้าจอ",

            ["Pixels"] = "พิกเซล",
            ["Sensitivity"] = "ความไว",
            ["Jitter"] = "สั่น",
            ["Offset"] = "ออฟเซ็ต",
            ["Percent"] = "เปอร์เซ็นต์",
            ["Seconds"] = "วินาที",
            ["Frames"] = "เฟรม",
            ["Amount"] = "ระดับ",
            ["Size"] = "ขนาด",
            ["Radius"] = "รัศมี",
            ["Thickness"] = "ความหนา",
            ["% Confidence"] = "% ความมั่นใจ",

            ["Closest to Center Screen"] = "ใกล้กึ่งกลางจอที่สุด",
            ["Closest to Mouse"] = "ใกล้เมาส์ที่สุด",
            ["Center"] = "กึ่งกลาง",
            ["Exponential"] = "เอ็กซ์โปเนนเชียล",
            ["Linear"] = "เชิงเส้น",
            ["Adaptive"] = "ปรับอัตโนมัติ",
            ["Shall0e's Prediction"] = "การคาดการณ์แบบ Shall0e",
            ["wisethef0x's EMA Prediction"] = "การคาดการณ์ EMA ของ wisethef0x",

            ["Loading local files..."] = "กำลังโหลดไฟล์ในเครื่อง...",
            ["Failed to load local files"] = "โหลดไฟล์ในเครื่องไม่สำเร็จ",
            ["Loaded Model: N/A"] = "โมเดลที่โหลด: ยังไม่มี",
            ["Loaded Config: N/A"] = "คอนฟิกที่โหลด: ยังไม่มี",
            ["Drag & Drop Media Here"] = "ลากไฟล์ภาพมาวางที่นี่",
            ["No File Located"] = "ยังไม่ได้เลือกไฟล์",
            ["Brightness"] = "ความสว่าง",
            ["Media Control"] = "ควบคุมภาพพื้นหลัง",
            ["ESP Color"] = "สี ESP",
            ["Error: Only PNG/JPG/JPEG images are supported"] = "รองรับเฉพาะไฟล์ภาพ PNG/JPG/JPEG",
            ["Invalid Media File"] = "ไฟล์ภาพไม่ถูกต้อง",
            ["Local Models"] = "โมเดลในเครื่อง",
            ["Local Configs"] = "คอนฟิกในเครื่อง",
            ["Available Models"] = "โมเดลที่พร้อมใช้",
            ["Available Configs"] = "คอนฟิกที่พร้อมใช้",
            ["No local models found."] = "ไม่พบโมเดลในเครื่อง",
            ["No local configs found."] = "ไม่พบคอนฟิกในเครื่อง",
            ["Loading system specs..."] = "กำลังโหลดสเปกเครื่อง...",
            ["Razer Synapse (Require Razer Peripheral)"] = "Razer Synapse (ต้องมีอุปกรณ์ Razer)",
            ["Cubic Bezier"] = "โค้ง Cubic Bezier",

            ["SUCCESS"] = "สำเร็จ",
            ["WARNING"] = "คำเตือน",
            ["ERROR"] = "ข้อผิดพลาด",
            ["INFO"] = "ข้อมูล",

            ["Turn aim assist on or off. You must load a model first."] = "เปิดหรือปิดระบบช่วยเล็ง ต้องโหลดโมเดลก่อนใช้งาน",
            ["Always track targets without holding a key. When off, you must hold the aim keybind."] = "ติดตามเป้าได้ตลอดโดยไม่ต้องกดค้าง ถ้าปิดต้องกดปุ่มช่วยเล็งค้างไว้",
            ["Lock onto a target until it moves out of range instead of switching targets."] = "ล็อกเป้าเดิมจนหลุดระยะ แทนการสลับเป้าบ่อย",
            ["How far a target must move before switching to a new one. Higher = stays locked longer."] = "กำหนดระยะที่เป้าต้องขยับก่อนสลับเป้าใหม่ ค่ายิ่งสูงยิ่งล็อกนาน",
            ["The key you hold to activate aim assist."] = "ปุ่มที่ต้องกดค้างเพื่อใช้งานช่วยเล็ง",
            ["An alternate key to activate aim assist."] = "ปุ่มสำรองสำหรับใช้งานช่วยเล็ง",
            ["How mouse movements are sent. Try different options if aim assist isn't working."] = "วิธีส่งคำสั่งการขยับเมาส์ ถ้าใช้งานไม่ได้ให้ลองเปลี่ยนตัวเลือก",
            ["The curve style used when moving to a target. Affects how natural the movement looks."] = "รูปแบบเส้นทางเมาส์ขณะเล็งไปยังเป้า มีผลต่อความเป็นธรรมชาติ",
            ["How targets are prioritized. Center screen is best for most games."] = "วิธีจัดลำดับเป้าหมาย โดยทั่วไปเลือกใกล้กลางจอเหมาะที่สุด",
            ["Where to aim on the detected target box. Center is usually best."] = "ตำแหน่งที่จะเล็งในกรอบเป้าหมาย โดยปกติเล็งกลางกรอบดีที่สุด",
            ["How fast the aim moves. Lower = faster and snappier, higher = slower and smoother."] = "ความเร็วการเล็ง ค่าต่ำจะเร็วและไว ค่าสูงจะช้าลงแต่นุ่มขึ้น",
            ["Adds random small movements to make aim look more human-like."] = "เพิ่มการขยับเล็กน้อยแบบสุ่มให้การเล็งดูเป็นธรรมชาติ",
            ["Enable the Y Offset (%) slider to adjust aim vertically by percentage."] = "เปิดใช้การปรับแกน Y แบบเปอร์เซ็นต์",
            ["Enable the X Offset (%) slider to adjust aim horizontally by percentage."] = "เปิดใช้การปรับแกน X แบบเปอร์เซ็นต์",
            ["Move aim point up (negative) or down (positive) in pixels."] = "เลื่อนจุดเล็งขึ้น (ค่าลบ) หรือลง (ค่าบวก) แบบพิกเซล",
            ["Move aim point up or down as a percentage of the target box height."] = "เลื่อนจุดเล็งขึ้นหรือลงตามเปอร์เซ็นต์ความสูงกรอบเป้า",
            ["Move aim point left (negative) or right (positive) in pixels."] = "เลื่อนจุดเล็งซ้าย (ค่าลบ) หรือขวา (ค่าบวก) แบบพิกเซล",
            ["Move aim point left or right as a percentage of the target box width."] = "เลื่อนจุดเล็งซ้ายหรือขวาตามเปอร์เซ็นต์ความกว้างกรอบเป้า",
            ["Predict where a moving target will be. Helps track fast-moving targets."] = "คาดการณ์ตำแหน่งเป้าที่กำลังเคลื่อนที่ ช่วยตามเป้าเร็วได้ดีขึ้น",
            ["The algorithm used to predict target movement. Try different ones to see what works best."] = "อัลกอริทึมสำหรับคาดการณ์การเคลื่อนที่ของเป้า ลองหลายแบบเพื่อหาแบบที่เหมาะ",
            ["How far ahead to predict target position. Higher = more prediction, may overshoot."] = "ระยะคาดการณ์ล่วงหน้า ค่ายิ่งสูงอาจนำเป้ามากเกินไป",
            ["How many frames ahead to predict. Higher = more prediction, may overshoot."] = "จำนวนเฟรมที่คาดการณ์ล่วงหน้า ค่ายิ่งสูงอาจนำเป้ามากเกินไป",
            ["Smooth out aim movements to reduce jitter and make tracking steadier."] = "ทำให้การเล็งนุ่มขึ้นเพื่อลดอาการสั่นและติดตามเป้าได้นิ่งขึ้น",
            ["How much smoothing to apply. Lower = smoother but slower, higher = faster but jittery."] = "ระดับความนุ่ม ค่าต่ำจะนิ่งแต่ช้า ค่าสูงจะเร็วแต่สั่นมากขึ้น",
            ["Automatically click when a target is detected in your crosshair area."] = "ยิงอัตโนมัติเมื่อพบเป้าในพื้นที่กากบาท",
            ["Only trigger when cursor is directly on target. More accurate but may miss some shots."] = "ยิงเมื่อเคอร์เซอร์ทับเป้าตรงๆ แม่นขึ้นแต่พลาดได้ง่ายขึ้น",
            ["Hold down fire instead of single clicks. Good for automatic weapons."] = "กดยิงค้างแทนการคลิกทีละนัด เหมาะกับปืนอัตโนมัติ",
            ["Wait time before firing after detecting a target. Helps avoid accidental shots."] = "เวลาหน่วงก่อนยิงหลังตรวจพบเป้า ช่วยลดการยิงพลาด",
            ["Show a circle on screen indicating the detection area."] = "แสดงวงบนหน้าจอเพื่อบอกพื้นที่ตรวจจับ",
            ["Change FOV size when holding a key. Useful for scoping in."] = "เปลี่ยนขนาด FOV เมื่อกดปุ่มค้าง เหมาะตอนซูมเล็ง",
            ["Adjust FOV position for third-person camera games."] = "ปรับตำแหน่ง FOV ให้เหมาะกับเกมมุมมองบุคคลที่สาม",
            ["The key to hold for switching to the dynamic FOV size."] = "ปุ่มที่กดค้างเพื่อสลับเป็น FOV แบบปรับได้",
            ["Shape of the FOV overlay. Circle is most common."] = "รูปทรงของ FOV โดยทั่วไปใช้วงกลม",
            ["Size of the detection area. Smaller = more precise, larger = wider coverage."] = "ขนาดพื้นที่ตรวจจับ เล็กจะแม่นกว่า ใหญ่จะครอบคลุมมากกว่า",
            ["FOV size when holding the Dynamic FOV key. Usually smaller for scoped aim."] = "ขนาด FOV เมื่อกดปุ่ม Dynamic FOV โดยมากจะใช้ขนาดเล็กตอนซูม",
            ["Draw a box around detected targets on screen."] = "วาดกรอบรอบเป้าหมายที่ตรวจพบ",
            ["Display how confident the AI is about each detection (0-100%)."] = "แสดงค่าความมั่นใจของ AI ต่อแต่ละเป้า (0-100%)",
            ["Draw lines from screen edge to detected targets."] = "วาดเส้นจากขอบจอไปยังเป้าที่ตรวจพบ",
            ["Where tracer lines start from on the screen."] = "ตำแหน่งที่เส้นชี้เป้าเริ่มจากบนหน้าจอ",
            ["Text size for the confidence percentage display."] = "ขนาดข้อความเปอร์เซ็นต์ความมั่นใจ",
            ["How rounded the detection box corners are. 0 = sharp corners."] = "ระดับความโค้งมุมของกรอบเป้า 0 คือมุมคม",
            ["How thick the detection box outline is."] = "ความหนาเส้นขอบกรอบเป้า",
            ["How see-through the detection box is. 0 = invisible, 1 = solid."] = "ความโปร่งใสของกรอบเป้า 0 คือไม่เห็น 1 คือทึบ",
            ["Resolution the AI uses for detection. Smaller = faster but less accurate."] = "ความละเอียดภาพที่ AI ใช้ตรวจจับ ค่ายิ่งเล็กยิ่งเร็วแต่แม่นน้อยลง",
            ["Which type of target to aim at. Best Confidence picks the most certain detection."] = "เลือกประเภทเป้าที่จะเล็ง โดยมั่นใจสูงสุดจะเลือกเป้าที่แน่ใจที่สุด",
            ["How sure the AI must be before targeting. Higher = fewer false detections but may miss targets."] = "ความมั่นใจขั้นต่ำก่อนเล็ง ค่าสูงลดการตรวจพลาดแต่เสี่ยงพลาดเป้าจริง",
            ["Allow switching between AI models using a hotkey."] = "อนุญาตให้สลับโมเดล AI ด้วยปุ่มลัด",
            ["Press this key to cycle through available AI models."] = "กดปุ่มนี้เพื่อสลับโมเดล AI ที่มีอยู่",
            ["Press this key to immediately stop all aim assist functions."] = "กดปุ่มนี้เพื่อหยุดฟังก์ชันช่วยเล็งทั้งหมดทันที",
            ["Save screenshots of detections for training new AI models."] = "บันทึกภาพจากการตรวจจับเพื่อใช้เทรนโมเดลใหม่",
            ["Automatically label collected screenshots with detection data."] = "ติดป้ายข้อมูลให้ภาพที่เก็บไว้โดยอัตโนมัติ",
            ["Show a visual effect on the UI when moving your mouse."] = "แสดงเอฟเฟกต์บนหน้าต่างเมื่อขยับเมาส์",
            ["Keep this window above all other windows."] = "ให้หน้าต่างนี้อยู่บนสุดเสมอ",
            ["Show extra information useful for troubleshooting problems."] = "แสดงข้อมูลเพิ่มเติมสำหรับวิเคราะห์ปัญหา",
            ["Save your current settings to a file you can load later."] = "บันทึกค่าปัจจุบันเป็นไฟล์เพื่อเรียกใช้ภายหลัง",
            ["How the screen is captured. DirectX is faster, GDI+ works on more systems."] = "วิธีจับภาพหน้าจอ DirectX เร็วกว่า ส่วน GDI+ รองรับเครื่องหลากหลายกว่า",
            ["Hide the overlay from screen recordings and streams. - Appears in system tray."] = "ซ่อนโอเวอร์เลย์ไม่ให้ติดในสตรีมหรือการอัดหน้าจอ (จะมีไอคอนที่ System Tray)",
            ["Update the list of available monitors."] = "อัปเดตรายการหน้าจอที่ใช้งานได้",
            ["Please load a model first"] = "กรุณาโหลดโมเดลก่อน",
            ["The Mouse Sensitivity you have set can cause Redskull to be unable to aim, please decrease if you suffer from this problem"] = "ค่าความไวเมาส์ที่ตั้งไว้สูงเกินไป อาจทำให้เล็งไม่เข้าเป้า แนะนำให้ลดลง",
            ["The Mouse Sensitivity you have set can cause Redskull to be unstable to aim, please increase if you suffer from this problem"] = "ค่าความไวเมาส์ที่ตั้งไว้ต่ำเกินไป อาจทำให้การเล็งไม่นิ่ง แนะนำให้เพิ่มขึ้น",
            ["The minimum confidence you have set for Redskull to be too high and may be unable to detect players."] = "ค่าความมั่นใจขั้นต่ำที่ตั้งไว้สูงเกินไป อาจตรวจจับผู้เล่นไม่ได้",
            ["The minimum confidence you have set for Redskull may be too low can cause false positives."] = "ค่าความมั่นใจขั้นต่ำที่ตั้งไว้ต่ำเกินไป อาจตรวจจับพลาดได้",
            ["Display list refreshed successfully."] = "รีเฟรชรายการหน้าจอเรียบร้อยแล้ว",
            ["[Emergency Stop Keybind] Disabled all AI features."] = "[ปุ่มหยุดฉุกเฉิน] ปิดฟังก์ชัน AI ทั้งหมดแล้ว",
        };

        private static readonly Dictionary<string, string> PrefixTranslations = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Loaded Model: "] = "โมเดลที่โหลด: ",
            ["Loaded Config: "] = "คอนฟิกที่โหลด: ",
            ["Directory not found: "] = "ไม่พบโฟลเดอร์: ",
            ["Failed to open folder: "] = "เปิดโฟลเดอร์ไม่สำเร็จ: ",
            ["Duplicate model renamed: "] = "พบชื่อโมเดลซ้ำ เปลี่ยนชื่อเป็น: ",
            ["Model moved: "] = "ย้ายโมเดลแล้ว: ",
            ["Error moving model: "] = "เกิดข้อผิดพลาดขณะย้ายโมเดล: ",
            ["Duplicate config renamed: "] = "พบชื่อคอนฟิกซ้ำ เปลี่ยนชื่อเป็น: ",
            ["Config moved: "] = "ย้ายคอนฟิกแล้ว: ",
            ["Error moving config: "] = "เกิดข้อผิดพลาดขณะย้ายคอนฟิก: ",
            ["Failed to load local files: "] = "โหลดไฟล์ในเครื่องไม่สำเร็จ: ",
            ["Display "] = "หน้าจอ ",
            ["Error clearing media: "] = "ล้างภาพพื้นหลังไม่สำเร็จ: ",
            ["Image size set to "] = "ตั้งค่าขนาดภาพเป็น ",
            ["Image size changing to "] = "กำลังเปลี่ยนขนาดภาพเป็น ",
            ["Successfully changed image size to "] = "เปลี่ยนขนาดภาพสำเร็จเป็น ",
            ["Error changing image size: "] = "เปลี่ยนขนาดภาพไม่สำเร็จ: ",
            ["Error refreshing displays: "] = "รีเฟรชรายการหน้าจอไม่สำเร็จ: ",
            ["AI focus switched to Display "] = "เปลี่ยนการโฟกัส AI ไปที่หน้าจอ ",
            ["Model imported: "] = "นำเข้าโมเดลแล้ว: ",
            ["Config imported: "] = "นำเข้าคอนฟิกแล้ว: ",
            ["Error importing model: "] = "นำเข้าโมเดลไม่สำเร็จ: ",
            ["Error importing config: "] = "นำเข้าคอนฟิกไม่สำเร็จ: ",
        };

        public static string Translate(string? text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text ?? string.Empty;
            }

            if (ExactTranslations.TryGetValue(text, out var translated))
            {
                return translated;
            }

            foreach (var (prefix, replacementPrefix) in PrefixTranslations)
            {
                if (text.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                {
                    return replacementPrefix + text[prefix.Length..];
                }
            }

            return text;
        }
    }
}

